# Generated by Django 4.2.4 on 2023-12-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_rename_yazar_yorum_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.post', unique=True),
        ),
    ]
