# Generated by Django 4.2.4 on 2023-12-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_yorum_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.yorum'),
        ),
    ]
