# Generated by Django 4.2.4 on 2023-12-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_remove_post_comments_yorum_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.post'),
        ),
    ]
