# Generated by Django 4.2.4 on 2023-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='title_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
