# Generated by Django 4.2.4 on 2023-12-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_tags_title_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.posttitle'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.posttitle'),
        ),
    ]
