# Generated by Django 4.2.4 on 2023-12-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_posttitle_alter_post_title_alter_tags_title_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='PostTitle',
        ),
    ]
