# Generated by Django 4.2.4 on 2023-12-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_alter_post_title_alter_tags_title_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='title_count',
        ),
    ]
