# Generated by Django 4.2.4 on 2023-12-16 20:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=['post', 'author'], unique=True),
        ),
    ]
