# Generated by Django 4.2.4 on 2023-12-16 20:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_yorum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='generate_slug', unique=True),
        ),
    ]
