# Generated by Django 4.2.4 on 2023-12-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_name_userprofile_isim_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
